### ISSUE TITLE
Many assemblies are broken as fuck

### ISSUE THREAD

**Issue by dalmationer** [lizardqueenlexi/orbstation#188]
Assemblies used inhands while attached to a singletank bomb seem to only cause sparking. Remote signallers sometimes work properly, and so do voice assemblies, but many others work inconsistently, especially timers and proximity sensors.
This may be an issue with grenade assemblies too, but I haven't checked them yet.
I'm surprised this issue hasn't been raised yet-- as far as I found I couldn't find one referring to this. If it's a skill issue of me doing something wrong when I'm making these assemblies, feel free to disregard.

**Reproduction:**

1. Attach an assembly trigger (e.g. prox sensor, timer, infrared) and igniter together. Note that while they are attached, you can usually activate them inhands to open their user interface (except in the case of the voice analyser, which does not allow you to do this.)
2. Attach the assembly to a singletank, optionally boring a pressure hole with a welder.
3. Use the item inhands. It will just spark, rather than opening the item's UI menu.

[video](https://www.youtube.com/watch?v=l2wLLFgzR60)

ALSO timers don't loop properly when attached to signaller assemblies.

**Comment by SuperSayu** [comment]
I have only started looking into it, but it looks like the reason you can't in-hand a one tank bomb and get its UI is because... eh, hard to sum up in a sentence.

Basically, they're using TGUI with an in-hands checker.  When the assembly creates a tgui, it runs a chain of procs essentially asking, "Is the target device currently in your hands?"  Assemblies use a hook so that this still works when you combine two assemblies together (creating an item called an assembly holder) but they didn't extend these checks so that when the holder is part of a one-tank bomb, that also counts.  So TGUI sees that an object in your hands isn't the one with the window, and just... farts in your general direction.

It sparks because every part of an assembly holder receives the attack-self, and that's just what igniters do.

If I'm right that part of it is a one line patch, we'll see

**Comment by Profakos** [comment]
This is fixed in the next version.

**Comment by lizardqueenlexi** [comment]
Resolved in #240
