### ISSUE TITLE
Change: Remove references to slur for Inuit/Yupik peoples

### ISSUE THREAD

**Issue by everanix** [lizardqueenlexi/orbstation#26]
Rename "eskimo shovel" to "snow shovel"
Rename /mob/living/simple_animal/hostile/skeleton/eskimo to  /mob/living/simple_animal/hostile/skeleton/snowSkeleton and remove the spear from its loot list
Updated all references to aforementioned mob in maps

**Comment by lizardqueenlexi** [comment]
Resolved in #31 

Well, mostly. The slur was removed, but since the spear is part of the sprite itself, I took PL's suggestion as reflavoring this particular skeleton as the "survivor" of some unspecified incident. That way, the spear isn't actually out of place (since it's the improvised spear you can make anyway).
