### ISSUE TITLE
Change: Hunger Rebalance

### ISSUE THREAD

**Issue by lizardqueenlexi** [lizardqueenlexi/orbstation#27]
It's obvious that hunger sucks. It's a constant problem, it makes the game miserable to play because of how much it slows you down and drains your stamina, it decreases _really fast_ (sometimes you get hungry within 2 minutes of roundstart), and there's nothing you can do about it with just the food that spawns on the station. If you don't have botany, cargo, and the kitchen staffed, and even then if you don't have a cook who is working constantly and intimately familiar with the dietary requirements of the various available species, it's a losing battle every time. Thus, for the game to remain remotely fun, we should change how hunger works.

PROPOSALS:
- Make the hunger bar decrease more slowly, and begin at a consistent (decently high) level instead of a random one.
- Make junk food at least a _little_ more effective at dealing with hunger - even if it's worse than actual food.
- Add roundstart/easily accessible food for all species. Especially lizards, who can't eat donk-pockets or pizza. (Allegedly, food crates for other species are coming to cargo soon, at least.)
- Make the hunger debuffs less harsh. It doesn't help that hunger compounds with mood to debuff you even further than it does on its own.

**Comment by skylord-a52** [comment]
Proposal: Moths eating clothes is fun and funny, but they get SO much satiation and joy from them, making hunger a complete non-issue. They should probably have a slightly lower bonus to both, being essentially "raw".

**Comment by Jacquerel** [comment]
> 

Perhaps eating a jumpsuit should give moths a temporary "digesting" debuff which makes them slow down as a tradeoff. Eating a whole shirt is a lot of food!

**Comment by Profakos** [comment]
The way hunger works, for reference:

Hunger does not slow you down, the -12 mood for starving causes the sanity loss that brings you to slowdown.

Hunger rate is affected by mood. Fact: if you turn off mood, hunger will cause direct slowdown!

Satiety is also a healthiness stat. It gives you defense against viruses, for example. If it goes below 0, your passive hunger rate *triples*. Satiety decreases by eating junkfood, each bite decreases it by its junkiness amount. Satiety from junkfood bottoms out at -200, and you can't eat junkfood at -150, unless if you are starving, or is voracious.

Junkfood are Okay at dealing with hunger, as they have two kinds of nutriment, sugar and... nutriment. Sugar is basically just a slightly worse nutriment that gets absorbed faster. Fact: to make a food be good at nutrition, it need various kinds of reagents with nutrition value, because then they get absorbed at the same time. 

Hunger also decreases when you move (faster if you run), when you are healing from blood loss or organ damage. 

It is possible to print cyber stomachs and stomach implants.

**Comment by Jacquerel** [comment]
> 

https://github.com/tgstation/tgstation/pull/67537#issuecomment-1146746041
It appears this was never within the original design intentions for moths and they're making some attempt to fix it upstream now too.

**Comment by lizardqueenlexi** [comment]
We haven't had any major complaints about food in quite some time now. Orderable supply crates for various species seem to have dealt with a lot of the issues. I'm closing this until any other major complaints come up.
